USE [master]
GO
-- エラーが出る場合、C:\testDB　フォルダがあるか確認してください。
CREATE DATABASE [AvaNyadeEmployee] ON  PRIMARY 
( NAME = N'AvaNyadeEmployee',		FILENAME = N'C:\testDB\AvaNyadeEmployee.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'AvaNyadeEmployee_log',	FILENAME = N'C:\testDB\AvaNyadeEmployee_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'AvaNyadeEmployee'
GO

-- SQL Server 2008 (100)、SQL Server 2012 (110)、SQL Server 2014 (120)、SQL Server 2016 (130)、SQL Server 2017 (140) 
ALTER DATABASE [AvaNyadeEmployee] SET COMPATIBILITY_LEVEL = 120  -- Visual Studio 2017 互換用　120->100
-- 確認
-- SELECT compatibility_level FROM sys.databases WHERE name = 'AvaNyadeEmployee';  
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AvaNyadeEmployee].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AvaNyadeEmployee] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AvaNyadeEmployee] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AvaNyadeEmployee] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AvaNyadeEmployee] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AvaNyadeEmployee] SET ARITHABORT OFF 
GO
ALTER DATABASE [AvaNyadeEmployee] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AvaNyadeEmployee] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [AvaNyadeEmployee] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AvaNyadeEmployee] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AvaNyadeEmployee] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AvaNyadeEmployee] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AvaNyadeEmployee] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AvaNyadeEmployee] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AvaNyadeEmployee] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AvaNyadeEmployee] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AvaNyadeEmployee] SET  ENABLE_BROKER 
GO
ALTER DATABASE [AvaNyadeEmployee] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AvaNyadeEmployee] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AvaNyadeEmployee] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AvaNyadeEmployee] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AvaNyadeEmployee] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AvaNyadeEmployee] SET  READ_WRITE 
GO
ALTER DATABASE [AvaNyadeEmployee] SET RECOVERY FULL 
GO
ALTER DATABASE [AvaNyadeEmployee] SET  MULTI_USER 
GO
ALTER DATABASE [AvaNyadeEmployee] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AvaNyadeEmployee] SET DB_CHAINING OFF 
